---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-playbooks-persistentvolumeclaim
  namespace: semaphore
  annotations:
    nfs.io/storage-path: semaphore/playbooks
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-shared-persistentvolumeclaim
  namespace: semaphore
  annotations:
    nfs.io/storage-path: semaphore/shared
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
