---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemos-deployment
  namespace: nfs-testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxdemos-deployment
  template:
    metadata:
      labels:
        app: nginxdemos-deployment
        version: latest
    spec:
      containers:
        - name: nginxdemos-hello
          image: paulosalgado/nginxdemos-hello:latest
          resources:
            requests:
              memory: "40Mi"
              cpu: "0.010"
            limits:
              memory: "50Mi"
              cpu: "0.020"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nginxdemos-persistentvolumeclaim
