---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-persistentvolumeclaim
  namespace: semaphore
  annotations:
    nfs.io/storage-path: mariadb
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
