---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: semaphore
spec:
  ports:
    - name: http-port
      port: 3306
      targetPort: http-port
      protocol: TCP
  selector:
    app: mariadb-deployment
